// Code generated by MockGen. DO NOT EDIT.
// Source: golang-redis/service (interfaces: LockService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_service/lock.go golang-redis/service LockService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	service "golang-redis/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLockService is a mock of LockService interface.
type MockLockService struct {
	ctrl     *gomock.Controller
	recorder *MockLockServiceMockRecorder
	isgomock struct{}
}

// MockLockServiceMockRecorder is the mock recorder for MockLockService.
type MockLockServiceMockRecorder struct {
	mock *MockLockService
}

// NewMockLockService creates a new mock instance.
func NewMockLockService(ctrl *gomock.Controller) *MockLockService {
	mock := &MockLockService{ctrl: ctrl}
	mock.recorder = &MockLockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockService) EXPECT() *MockLockServiceMockRecorder {
	return m.recorder
}

// RunCriticalSection mocks base method.
func (m *MockLockService) RunCriticalSection(ctx context.Context, req service.RunCriticalSectionRequest) (*service.RunCriticalSectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCriticalSection", ctx, req)
	ret0, _ := ret[0].(*service.RunCriticalSectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunCriticalSection indicates an expected call of RunCriticalSection.
func (mr *MockLockServiceMockRecorder) RunCriticalSection(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCriticalSection", reflect.TypeOf((*MockLockService)(nil).RunCriticalSection), ctx, req)
}
