// Code generated by MockGen. DO NOT EDIT.
// Source: golang-redis/service (interfaces: PubSubService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_service/pubsub.go golang-redis/service PubSubService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	service "golang-redis/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPubSubService is a mock of PubSubService interface.
type MockPubSubService struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubServiceMockRecorder
	isgomock struct{}
}

// MockPubSubServiceMockRecorder is the mock recorder for MockPubSubService.
type MockPubSubServiceMockRecorder struct {
	mock *MockPubSubService
}

// NewMockPubSubService creates a new mock instance.
func NewMockPubSubService(ctrl *gomock.Controller) *MockPubSubService {
	mock := &MockPubSubService{ctrl: ctrl}
	mock.recorder = &MockPubSubServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSubService) EXPECT() *MockPubSubServiceMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPubSubService) Publish(ctx context.Context, req service.PublishRequest) (*service.PublishResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, req)
	ret0, _ := ret[0].(*service.PublishResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockPubSubServiceMockRecorder) Publish(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPubSubService)(nil).Publish), ctx, req)
}

// RunConsumer mocks base method.
func (m *MockPubSubService) RunConsumer(ctx context.Context, channel, consumerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunConsumer", ctx, channel, consumerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunConsumer indicates an expected call of RunConsumer.
func (mr *MockPubSubServiceMockRecorder) RunConsumer(ctx, channel, consumerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunConsumer", reflect.TypeOf((*MockPubSubService)(nil).RunConsumer), ctx, channel, consumerName)
}
