// Code generated by MockGen. DO NOT EDIT.
// Source: golang-redis/service (interfaces: RateLimiterService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_service/ratelimiter.go golang-redis/service RateLimiterService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	service "golang-redis/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRateLimiterService is a mock of RateLimiterService interface.
type MockRateLimiterService struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterServiceMockRecorder
	isgomock struct{}
}

// MockRateLimiterServiceMockRecorder is the mock recorder for MockRateLimiterService.
type MockRateLimiterServiceMockRecorder struct {
	mock *MockRateLimiterService
}

// NewMockRateLimiterService creates a new mock instance.
func NewMockRateLimiterService(ctrl *gomock.Controller) *MockRateLimiterService {
	mock := &MockRateLimiterService{ctrl: ctrl}
	mock.recorder = &MockRateLimiterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiterService) EXPECT() *MockRateLimiterServiceMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiterService) Allow(ctx context.Context, identifier string) (service.RateLimitDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, identifier)
	ret0, _ := ret[0].(service.RateLimitDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterServiceMockRecorder) Allow(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiterService)(nil).Allow), ctx, identifier)
}
