// Code generated by MockGen. DO NOT EDIT.
// Source: golang-redis/repository (interfaces: LockRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/lock.go golang-redis/repository LockRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-redis/repository"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLockRepository is a mock of LockRepository interface.
type MockLockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLockRepositoryMockRecorder
	isgomock struct{}
}

// MockLockRepositoryMockRecorder is the mock recorder for MockLockRepository.
type MockLockRepositoryMockRecorder struct {
	mock *MockLockRepository
}

// NewMockLockRepository creates a new mock instance.
func NewMockLockRepository(ctrl *gomock.Controller) *MockLockRepository {
	mock := &MockLockRepository{ctrl: ctrl}
	mock.recorder = &MockLockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockRepository) EXPECT() *MockLockRepositoryMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockLockRepository) Acquire(ctx context.Context, key string, ttl time.Duration) (repository.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, key, ttl)
	ret0, _ := ret[0].(repository.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockLockRepositoryMockRecorder) Acquire(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockLockRepository)(nil).Acquire), ctx, key, ttl)
}
