// Code generated by MockGen. DO NOT EDIT.
// Source: golang-redis/repository (interfaces: PubSubRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/pubsub.go golang-redis/repository PubSubRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-redis/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPubSubRepository is a mock of PubSubRepository interface.
type MockPubSubRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubRepositoryMockRecorder
	isgomock struct{}
}

// MockPubSubRepositoryMockRecorder is the mock recorder for MockPubSubRepository.
type MockPubSubRepositoryMockRecorder struct {
	mock *MockPubSubRepository
}

// NewMockPubSubRepository creates a new mock instance.
func NewMockPubSubRepository(ctrl *gomock.Controller) *MockPubSubRepository {
	mock := &MockPubSubRepository{ctrl: ctrl}
	mock.recorder = &MockPubSubRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSubRepository) EXPECT() *MockPubSubRepositoryMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPubSubRepository) Publish(ctx context.Context, channel, payload string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, channel, payload)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockPubSubRepositoryMockRecorder) Publish(ctx, channel, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPubSubRepository)(nil).Publish), ctx, channel, payload)
}

// Subscribe mocks base method.
func (m *MockPubSubRepository) Subscribe(ctx context.Context, channel string) (<-chan repository.Message, func() error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, channel)
	ret0, _ := ret[0].(<-chan repository.Message)
	ret1, _ := ret[1].(func() error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockPubSubRepositoryMockRecorder) Subscribe(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockPubSubRepository)(nil).Subscribe), ctx, channel)
}
