// Code generated by MockGen. DO NOT EDIT.
// Source: golang-redis/repository (interfaces: RateLimiterRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/ratelimiter.go golang-redis/repository RateLimiterRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-redis/repository"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRateLimiterRepository is a mock of RateLimiterRepository interface.
type MockRateLimiterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterRepositoryMockRecorder
	isgomock struct{}
}

// MockRateLimiterRepositoryMockRecorder is the mock recorder for MockRateLimiterRepository.
type MockRateLimiterRepositoryMockRecorder struct {
	mock *MockRateLimiterRepository
}

// NewMockRateLimiterRepository creates a new mock instance.
func NewMockRateLimiterRepository(ctrl *gomock.Controller) *MockRateLimiterRepository {
	mock := &MockRateLimiterRepository{ctrl: ctrl}
	mock.recorder = &MockRateLimiterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiterRepository) EXPECT() *MockRateLimiterRepositoryMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiterRepository) Allow(ctx context.Context, key string, limit int, window time.Duration) (repository.RateLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, key, limit, window)
	ret0, _ := ret[0].(repository.RateLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterRepositoryMockRecorder) Allow(ctx, key, limit, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiterRepository)(nil).Allow), ctx, key, limit, window)
}
